bash simulaiton/data_collection/batch_run/weather-0/town_town01_0.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town01_1.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town02_0.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town02_1.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town03_0.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town03_1.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town04_0.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town04_1.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town05_0.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town05_1.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town06_0.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town06_1.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town07_0.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town07_1.sh & 
bash simulaiton/data_collection/batch_run/weather-0/town_town10_0.sh & 
